'use client';

import { DragEvent, FormEvent, ReactNode, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, Film, GripVertical, LayoutDashboard, MapPin, Plus, Sparkles, Ticket, Users } from 'lucide-react';
import './xinema.css';

type View = 'welcome' | 'agenda' | 'programming' | 'team';
type Room = { id: string; name: string; capacity: number; format: string };
type Movie = { imdbId: string; title: string; year: string; posterUrl: string | null; durationMin?: number; plot?: string | null; director?: string | null; actors?: string | null; genre?: string | null; rated?: string | null };
type Screening = { id: number; title: string; roomId: string; day: number; time: string; duration: number; buffer: number; format: string; posterUrl?: string | null; imdbId?: string };
type DragPayload = { kind: 'movie'; movie: Movie } | { kind: 'screening'; screeningId: number };

const rooms: Room[] = [{ id: 'imax', name: 'Salle 1', capacity: 250, format: 'IMAX' }, { id: 'classic', name: 'Salle 2', capacity: 120, format: 'Premium' }];
const days = [{ name: 'lundi', date: '13 avr.' }, { name: 'mardi', date: '14 avr.' }, { name: 'mercredi', date: '15 avr.' }, { name: 'jeudi', date: '16 avr.' }, { name: 'vendredi', date: '17 avr.' }, { name: 'samedi', date: '18 avr.' }, { name: 'dimanche', date: '19 avr.' }];
const initialScreenings: Screening[] = [
  { id: 1, title: 'Dune : Deuxième partie', roomId: 'imax', day: 0, time: '13:40', duration: 166, buffer: 20, format: 'VO IMAX' },
  { id: 2, title: 'Le Comte de Monte-Cristo', roomId: 'classic', day: 0, time: '16:10', duration: 178, buffer: 15, format: 'VF' },
  { id: 3, title: 'Vice-Versa 2', roomId: 'imax', day: 0, time: '18:25', duration: 96, buffer: 15, format: 'VF' },
  { id: 4, title: 'Furiosa', roomId: 'classic', day: 1, time: '14:15', duration: 148, buffer: 15, format: 'VO' },
  { id: 5, title: 'Un p’tit truc en plus', roomId: 'imax', day: 2, time: '10:30', duration: 99, buffer: 15, format: 'VF' },
];
const hours = Array.from({ length: 18 }, (_, i) => i + 8);
const dragType = 'application/x-xinema';

export default function XInemaPage() {
  const [view, setView] = useState<View>('welcome');
  const [screenings, setScreenings] = useState(initialScreenings);
  const [team, setTeam] = useState(['Alice Dupont', 'Thomas Bernard', 'Maya Khelifi', 'Louis Martin']);
  const [selectedDay, setSelectedDay] = useState(0);
  const [selectedRoomId, setSelectedRoomId] = useState(rooms[0].id);
  const [showPlanner, setShowPlanner] = useState(false);
  const [filmTitle, setFilmTitle] = useState('');
  const [movieSearch, setMovieSearch] = useState('');
  const [movieResults, setMovieResults] = useState<Movie[]>([]);
  const [movieMessage, setMovieMessage] = useState('');
  const [selectedMovie, setSelectedMovie] = useState<Movie | null>(null);
  const [screeningTime, setScreeningTime] = useState('20:30');
  const [bufferMinutes, setBufferMinutes] = useState(15);
  const [employeeName, setEmployeeName] = useState('');
  const [availability, setAvailability] = useState<'available' | 'unavailable'>('available');
  const dayScreenings = useMemo(() => screenings.filter((s) => s.day === selectedDay), [screenings, selectedDay]);

  useEffect(() => {
    const query = movieSearch.trim();
    if (query.length < 2) { setMovieResults([]); setMovieMessage(''); return; }
    const controller = new AbortController();
    const timer = window.setTimeout(async () => {
      setMovieMessage('Recherche IMDb…');
      try {
        const response = await fetch(`/api/xinema/movies?q=${encodeURIComponent(query)}`, { signal: controller.signal });
        const payload = await response.json() as { movies?: Movie[]; error?: string; message?: string };
        if (!response.ok) throw new Error(payload.error ?? 'La recherche est indisponible.');
        setMovieResults(payload.movies ?? []);
        setMovieMessage(payload.message ?? (payload.movies?.length ? 'Sélectionnez un film pour voir sa fiche.' : 'Aucun film trouvé.'));
      } catch (error) { if ((error as Error).name !== 'AbortError') { setMovieResults([]); setMovieMessage((error as Error).message || 'La recherche est indisponible.'); } }
    }, 350);
    return () => { controller.abort(); window.clearTimeout(timer); };
  }, [movieSearch]);

  async function selectMovie(movie: Movie) {
    setSelectedMovie(movie); setFilmTitle(movie.title); setMovieMessage('Chargement de la fiche IMDb…');
    try {
      const response = await fetch(`/api/xinema/movies?id=${encodeURIComponent(movie.imdbId)}`);
      const payload = await response.json() as { movie?: Movie; error?: string };
      if (!response.ok || !payload.movie) throw new Error(payload.error);
      setSelectedMovie(payload.movie); setFilmTitle(payload.movie.title); setMovieMessage(`${payload.movie.durationMin ?? 120} min · IMDb ${payload.movie.imdbId}`);
    } catch { setMovieMessage('Film sélectionné · durée par défaut : 120 min.'); }
  }
  function addScreening(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!filmTitle.trim()) return;
    setScreenings((items) => [...items, { id: Date.now(), title: filmTitle.trim(), roomId: selectedRoomId, day: selectedDay, time: screeningTime, duration: selectedMovie?.durationMin ?? 120, buffer: bufferMinutes, format: selectedMovie ? 'IMDb' : 'À confirmer', posterUrl: selectedMovie?.posterUrl, imdbId: selectedMovie?.imdbId }]);
    setShowPlanner(false);
  }
  function addMovieToAgenda(movie: Movie, roomId: string, hour: number) {
    setScreenings((items) => [...items, { id: Date.now(), title: movie.title, roomId, day: selectedDay, time: `${String(hour % 24).padStart(2, '0')}:00`, duration: movie.durationMin ?? 120, buffer: bufferMinutes, format: 'IMDb', posterUrl: movie.posterUrl, imdbId: movie.imdbId }]);
  }
  function moveScreening(id: number, roomId: string, hour: number) {
    setScreenings((items) => items.map((s) => s.id === id ? { ...s, roomId, day: selectedDay, time: `${String(hour % 24).padStart(2, '0')}:00` } : s));
  }
  function addEmployee(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (employeeName.trim()) { setTeam((items) => [...items, employeeName.trim()]); setEmployeeName(''); } }

  if (view === 'welcome') return <Welcome setView={setView} />;
  return <main className="xinema-app">
    <header className="xinema-topbar"><button className="xinema-wordmark" onClick={() => setView('welcome')}><Film size={20} /> XI<b>NÉMA</b></button><nav className="xinema-nav"><button className={view === 'agenda' ? 'is-active' : ''} onClick={() => setView('agenda')}><CalendarDays size={15} /> Agenda</button><button className={view === 'programming' ? 'is-active' : ''} onClick={() => setView('programming')}><Film size={15} /> Salles</button><button className={view === 'team' ? 'is-active' : ''} onClick={() => setView('team')}><Users size={15} /> Équipe</button></nav><div className="xinema-topbar__meta"><Sparkles size={15} /> Mode démo local</div><button className="xinema-back" onClick={() => setView('welcome')}><ArrowLeft size={16} /> Accueil</button></header>
    {view === 'agenda' && <AgendaView selectedDay={selectedDay} setSelectedDay={setSelectedDay} screenings={dayScreenings} selectedMovie={selectedMovie} setView={setView} onAddMovie={addMovieToAgenda} onMoveScreening={moveScreening} />}
    {view === 'programming' && <section className="xinema-shell"><div className="xinema-hero xinema-hero--manager"><div><p className="xinema-kicker">Programmation · {days[selectedDay].name} {days[selectedDay].date}</p><h1>Deux salles, un seul rythme.</h1><p>Choisissez un film, consultez sa fiche IMDb, puis programmez-le ou glissez-le dans l’agenda.</p></div><button className="xinema-primary" onClick={() => setShowPlanner(true)}><Plus size={17} /> Nouvelle projection</button></div><div className="xinema-stat-grid"><Stat icon={<Ticket />} value={String(dayScreenings.length)} label="Séances du jour" /><Stat icon={<MapPin />} value="370" label="Places dans le multiplexe" /><Stat icon={<Clock3 />} value={`${Math.round(screenings.reduce((sum, s) => sum + s.duration + s.buffer, 0) / 60)} h`} label="Temps de projection" /><Stat icon={<Users />} value={String(team.length)} label="Salariés actifs" /></div><DaySelector selectedDay={selectedDay} setSelectedDay={setSelectedDay} /><div className="xinema-section-heading"><div><p className="xinema-kicker">Programme du jour</p><h2>Projection par salle</h2></div><span className="xinema-status"><span /> Exploitation ouverte</span></div><div className="xinema-room-columns">{rooms.map((room) => <section className="xinema-room-card" key={room.id}><div className="xinema-room-card__header"><div><p>{room.name}</p><h3>{room.format}</h3></div><span>{room.capacity} places</span></div>{dayScreenings.filter((s) => s.roomId === room.id).sort((a, b) => a.time.localeCompare(b.time)).map((s) => <ScreeningCard key={s.id} screening={s} />)}{!dayScreenings.some((s) => s.roomId === room.id) && <div className="xinema-empty-room"><Film size={19} /> Aucune projection programmée</div>}</section>)}</div><FilmDiscovery movieSearch={movieSearch} setMovieSearch={setMovieSearch} movieResults={movieResults} movieMessage={movieMessage} selectedMovie={selectedMovie} selectMovie={selectMovie} onProgram={() => setShowPlanner(true)} />{showPlanner && <PlannerDialog filmTitle={filmTitle} setFilmTitle={setFilmTitle} selectedMovie={selectedMovie} screeningTime={screeningTime} setScreeningTime={setScreeningTime} selectedRoomId={selectedRoomId} setSelectedRoomId={setSelectedRoomId} bufferMinutes={bufferMinutes} setBufferMinutes={setBufferMinutes} onClose={() => setShowPlanner(false)} onSubmit={addScreening} />}</section>}
    {view === 'team' && <TeamView team={team} selectedDay={selectedDay} setSelectedDay={setSelectedDay} employeeName={employeeName} setEmployeeName={setEmployeeName} addEmployee={addEmployee} availability={availability} setAvailability={setAvailability} />}
  </main>;
}

function Welcome({ setView }: { setView: (view: View) => void }) { return <main className="xinema-home"><div className="xinema-home__backdrop" /><div className="xinema-home__grain" /><section className="xinema-home__content"><div className="xinema-brand"><span className="xinema-brand__mark"><Film size={22} /></span><span>XI<b>NÉMA</b></span></div><p className="xinema-kicker">Prototype intégré à XIRH</p><h1>L’écosystème numérique des salles premium.</h1><p className="xinema-home__intro">Une démonstration complète de gestion d’un cinéma multiplexe : agenda de direction, programmation multi-salles et planning d’équipe.</p><div className="xinema-portal-grid"><button className="xinema-portal-card" onClick={() => setView('agenda')}><span className="xinema-portal-card__icon"><LayoutDashboard size={24} /></span><span className="xinema-portal-card__eyebrow">Espace direction</span><strong>Agenda & programmation</strong><small>Suivre la semaine, les deux salles et les projections.</small><span className="xinema-portal-card__action">Ouvrir les tours de contrôle <ArrowRight size={16} /></span></button><button className="xinema-portal-card xinema-portal-card--team" onClick={() => setView('team')}><span className="xinema-portal-card__icon"><Users size={24} /></span><span className="xinema-portal-card__eyebrow">Espace équipe</span><strong>Planning & disponibilités</strong><small>Consulter l’équipe et ses créneaux de présence.</small><span className="xinema-portal-card__action">Accéder à l’équipe <ArrowRight size={16} /></span></button></div></section></main>; }

function AgendaView({ selectedDay, setSelectedDay, screenings, selectedMovie, setView, onAddMovie, onMoveScreening }: { selectedDay: number; setSelectedDay: (day: number) => void; screenings: Screening[]; selectedMovie: Movie | null; setView: (view: View) => void; onAddMovie: (movie: Movie, roomId: string, hour: number) => void; onMoveScreening: (id: number, roomId: string, hour: number) => void }) {
  const [hoveredRoom, setHoveredRoom] = useState<string | null>(null);
  const dragStart = (event: DragEvent<HTMLElement>, payload: DragPayload) => { event.dataTransfer.setData(dragType, JSON.stringify(payload)); event.dataTransfer.effectAllowed = payload.kind === 'movie' ? 'copy' : 'move'; };
  const drop = (event: DragEvent<HTMLDivElement>, roomId: string) => {
    event.preventDefault(); setHoveredRoom(null);
    const bounds = event.currentTarget.getBoundingClientRect();
    const hour = Math.max(8, Math.min(25, Math.round(((event.clientY - bounds.top) / 53) + 8)));
    try { const payload = JSON.parse(event.dataTransfer.getData(dragType)) as DragPayload; if (payload.kind === 'movie') onAddMovie(payload.movie, roomId, hour); else onMoveScreening(payload.screeningId, roomId, hour); } catch {}
  };
  return <section className="xinema-shell"><div className="xinema-agenda-hero"><div><p className="xinema-kicker">Tours de contrôle · direction</p><h1>Agenda du multiplexe</h1><p>La frise suit la durée réelle de chaque film, avec 10 minutes de bandes-annonces avant la séance.</p></div><button className="xinema-primary" onClick={() => setView('programming')}><Film size={17} /> Choisir un film</button></div><DaySelector selectedDay={selectedDay} setSelectedDay={setSelectedDay} /><div className="xinema-section-heading"><div><p className="xinema-kicker">Aujourd’hui · {days[selectedDay].name} {days[selectedDay].date}</p><h2>Agenda multi-salles</h2></div><span className="xinema-status"><span /> 2 salles ouvertes</span></div><div className="xinema-drop-tray">{selectedMovie ? <article className="xinema-drag-film" draggable onDragStart={(e) => dragStart(e, { kind: 'movie', movie: selectedMovie })}><img src={selectedMovie.posterUrl ?? '/xinema/movie-placeholder.png'} alt={`Affiche de ${selectedMovie.title}`} /><div><span><GripVertical size={15} /> Film prêt à programmer</span><strong>{selectedMovie.title}</strong><small>{selectedMovie.durationMin ?? 120} min · glissez-le vers un créneau</small></div></article> : <div><Film size={17} /> Choisissez un film dans <button onClick={() => setView('programming')}>Salles</button>, puis glissez-le ici.</div>}</div><div className="xinema-agenda-scroll"><div className="xinema-timeline"><div className="xinema-timeline__head"><div>Heure</div>{rooms.map((room) => <div key={room.id}>{room.name}<small>{room.format} · {room.capacity} places</small></div>)}</div><div className="xinema-timeline__body"><div className="xinema-timeline__hours">{hours.map((hour) => <div key={hour}>{String(hour % 24).padStart(2, '0')} h</div>)}</div>{rooms.map((room) => <TimelineRoom key={room.id} room={room} screenings={screenings.filter((s) => s.roomId === room.id)} hovered={hoveredRoom === room.id} setHovered={setHoveredRoom} dragStart={dragStart} drop={drop} />)}</div></div></div><div className="xinema-agenda-legend"><span><i className="xinema-legend-trailer" /> Bandes-annonces · 10 min</span><span><i className="xinema-legend-film" /> Film · durée réelle</span><span><i className="xinema-legend-buffer" /> Tampon pub / rotation</span></div></section>;
}
function TimelineRoom({ room, screenings, hovered, setHovered, dragStart, drop }: { room: Room; screenings: Screening[]; hovered: boolean; setHovered: (value: string | null) => void; dragStart: (event: DragEvent<HTMLElement>, payload: DragPayload) => void; drop: (event: DragEvent<HTMLDivElement>, roomId: string) => void }) { return <div className={`xinema-timeline__room${hovered ? ' is-drop-target' : ''}`} onDragOver={(event) => { event.preventDefault(); event.dataTransfer.dropEffect = 'move'; setHovered(room.id); }} onDragLeave={() => setHovered(null)} onDrop={(event) => drop(event, room.id)}>{screenings.map((screening) => <TimelineEvent key={screening.id} screening={screening} dragStart={dragStart} />)}</div>; }
function TimelineEvent({ screening, dragStart }: { screening: Screening; dragStart: (event: DragEvent<HTMLElement>, payload: DragPayload) => void }) { const [hoursPart, minutesPart] = screening.time.split(':').map(Number); const offset = ((hoursPart * 60 + minutesPart) - 480) * (53 / 60); const trailer = 10 * (53 / 60); const film = screening.duration * (53 / 60); const buffer = screening.buffer * (53 / 60); return <article className="xinema-timeline-event" style={{ top: offset, height: trailer + film + buffer }} draggable onDragStart={(event) => dragStart(event, { kind: 'screening', screeningId: screening.id })}><div className="xinema-timeline-event__trailer">Bandes-annonces · 10 min</div><div className="xinema-timeline-event__film" style={{ height: film }}><img src={screening.posterUrl ?? '/xinema/movie-placeholder.png'} alt="" /><div><span><GripVertical size={13} /> {screening.time}</span><strong>{screening.title}</strong><small>{screening.duration} min · {screening.format}</small></div></div><div className="xinema-timeline-event__buffer" style={{ height: buffer }}>Rotation · {screening.buffer} min</div></article>; }

function FilmDiscovery({ movieSearch, setMovieSearch, movieResults, movieMessage, selectedMovie, selectMovie, onProgram }: { movieSearch: string; setMovieSearch: (v: string) => void; movieResults: Movie[]; movieMessage: string; selectedMovie: Movie | null; selectMovie: (m: Movie) => void; onProgram: () => void }) { return <section className="xinema-film-discovery"><div className="xinema-section-heading"><div><p className="xinema-kicker">Catalogue connecté</p><h2>Rechercher sur IMDb</h2></div><span className="xinema-status"><span /> API sécurisée côté serveur</span></div><label className="xinema-search-field">Titre, ex. Inception<input value={movieSearch} onChange={(e) => setMovieSearch(e.target.value)} placeholder="Rechercher un film" /></label>{movieMessage && <p className="xinema-movie-message">{movieMessage}</p>}<div className="xinema-film-discovery__layout"><div className="xinema-movie-cards">{movieResults.map((movie) => <button type="button" className="xinema-movie-card" key={movie.imdbId} onClick={() => selectMovie(movie)}><img src={movie.posterUrl ?? '/xinema/movie-placeholder.png'} alt="" /><span><strong>{movie.title}</strong><small>{movie.year} · {movie.imdbId}</small></span></button>)}</div>{selectedMovie && <MovieDetail movie={selectedMovie} onProgram={onProgram} />}</div></section>; }
function MovieDetail({ movie, onProgram }: { movie: Movie; onProgram: () => void }) { return <article className="xinema-movie-detail"><img src={movie.posterUrl ?? '/xinema/movie-placeholder.png'} alt={`Affiche de ${movie.title}`} /><div><p className="xinema-kicker">Fiche IMDb · {movie.year}</p><h3>{movie.title}</h3><div className="xinema-film-facts"><span>{movie.durationMin ?? 120} min</span>{movie.rated && <span>{movie.rated}</span>}{movie.genre && <span>{movie.genre}</span>}</div><p>{movie.plot ?? 'Synopsis indisponible pour ce film.'}</p><dl><div><dt>Réalisation</dt><dd>{movie.director ?? 'Non renseignée'}</dd></div>{movie.actors && <div><dt>Distribution</dt><dd>{movie.actors}</dd></div>}</dl><button className="xinema-primary" onClick={onProgram}><Plus size={16} /> Programmer ce film</button></div></article>; }

function TeamView({ team, selectedDay, setSelectedDay, employeeName, setEmployeeName, addEmployee, availability, setAvailability }: { team: string[]; selectedDay: number; setSelectedDay: (d: number) => void; employeeName: string; setEmployeeName: (v: string) => void; addEmployee: (e: FormEvent<HTMLFormElement>) => void; availability: 'available' | 'unavailable'; setAvailability: (v: 'available' | 'unavailable') => void }) { return <section className="xinema-shell"><div className="xinema-hero xinema-hero--team"><div><p className="xinema-kicker">Agenda de l’équipe</p><h1>Chaque salle a son équipe.</h1><p>Visualisez les rotations de la semaine, les postes et les disponibilités du personnel.</p></div><button className="xinema-primary" onClick={() => setAvailability(availability === 'available' ? 'unavailable' : 'available')}><Check size={17} /> Je suis {availability === 'available' ? 'disponible' : 'indisponible'}</button></div><DaySelector selectedDay={selectedDay} setSelectedDay={setSelectedDay} /><div className="xinema-team-layout"><section className="xinema-panel xinema-panel--wide"><p className="xinema-kicker">Planning hebdomadaire</p><h2>Présences de l’équipe</h2><div className="xinema-staff-agenda"><div className="xinema-staff-agenda__head"><span>Collaborateur</span>{days.map((day) => <span key={day.date}>{day.name.slice(0, 3)}<small>{day.date}</small></span>)}</div>{team.map((member, index) => <div className="xinema-staff-agenda__row" key={member}><strong>{member}</strong>{days.map((day, dayIndex) => <span className={(index + dayIndex) % 5 === 0 ? 'is-off' : ''} key={day.date}>{(index + dayIndex) % 5 === 0 ? 'Repos' : index % 2 === 0 ? '12h–20h' : '16h–00h'}</span>)}</div>)}</div></section><section className="xinema-panel xinema-panel--form"><p className="xinema-kicker">Administration</p><h2>Registre du personnel</h2><p>Ajoutez un collaborateur et retrouvez-le immédiatement dans le planning de démonstration.</p><form onSubmit={addEmployee}><label>Prénom et nom<input value={employeeName} onChange={(e) => setEmployeeName(e.target.value)} placeholder="Ex. Camille Durand" /></label><button className="xinema-primary"><Plus size={16} /> Ajouter à l’équipe</button></form></section></div></section>; }
function HourRow({ hour, screenings, hoveredSlot, setHoveredSlot, dragStart, drop }: { hour: number; screenings: Screening[]; hoveredSlot: string | null; setHoveredSlot: (v: string | null) => void; dragStart: (e: DragEvent<HTMLElement>, p: DragPayload) => void; drop: (e: DragEvent<HTMLDivElement>, roomId: string, hour: number) => void }) { return <><div className="xinema-agenda-time">{String(hour % 24).padStart(2, '0')} h</div>{rooms.map((room) => { const session = screenings.find((s) => s.roomId === room.id && Number(s.time.slice(0, 2)) === hour); const slot = `${room.id}-${hour}`; return <div className={`xinema-agenda-slot${hoveredSlot === slot ? ' is-drop-target' : ''}`} key={slot} onDragOver={(e) => { e.preventDefault(); e.dataTransfer.dropEffect = 'move'; setHoveredSlot(slot); }} onDragLeave={() => setHoveredSlot(null)} onDrop={(e) => drop(e, room.id, hour)}>{session && <div className="xinema-agenda-session" draggable onDragStart={(e) => dragStart(e, { kind: 'screening', screeningId: session.id })}><GripVertical size={13} /><div><strong>{session.time} · {session.title}</strong><span>{session.duration} min + {session.buffer} min</span></div></div>}</div>; })}</>; }
function DaySelector({ selectedDay, setSelectedDay }: { selectedDay: number; setSelectedDay: (d: number) => void }) { return <div className="xinema-day-selector"><ChevronLeft size={17} />{days.map((day, i) => <button key={day.date} className={i === selectedDay ? 'is-active' : ''} onClick={() => setSelectedDay(i)}><span>{day.name.slice(0, 3)}</span><strong>{day.date.split(' ')[0]}</strong></button>)}<ChevronRight size={17} /></div>; }
function ScreeningCard({ screening }: { screening: Screening }) { return <article className="xinema-screening"><img src={screening.posterUrl ?? '/xinema/movie-placeholder.png'} alt="" /><div className="xinema-screening__time"><strong>{screening.time}</strong><span>{screening.duration} min</span></div><div className="xinema-screening__title"><h3>{screening.title}</h3><p>{screening.format} · tampon de {screening.buffer} min</p></div><span className="xinema-tag">Programmé</span></article>; }
function PlannerDialog(props: { filmTitle: string; setFilmTitle: (v: string) => void; selectedMovie: Movie | null; screeningTime: string; setScreeningTime: (v: string) => void; selectedRoomId: string; setSelectedRoomId: (v: string) => void; bufferMinutes: number; setBufferMinutes: (v: number) => void; onClose: () => void; onSubmit: (e: FormEvent<HTMLFormElement>) => void }) { return <div className="xinema-dialog-backdrop"><form className="xinema-dialog" onSubmit={props.onSubmit}><div><p className="xinema-kicker">Nouvelle projection</p><h2>Programmer une séance</h2></div>{props.selectedMovie ? <div className="xinema-dialog-film"><img src={props.selectedMovie.posterUrl ?? '/xinema/movie-placeholder.png'} alt="" /><span><strong>{props.selectedMovie.title}</strong><small>{props.selectedMovie.durationMin ?? 120} min · IMDb</small></span></div> : <p className="xinema-movie-message">Recherchez d’abord un film dans la section IMDb.</p>}<label>Film à programmer<input required value={props.filmTitle} onChange={(e) => props.setFilmTitle(e.target.value)} placeholder="Sélectionnez ou saisissez un film" /></label><div className="xinema-form-grid"><label>Salle<select value={props.selectedRoomId} onChange={(e) => props.setSelectedRoomId(e.target.value)}>{rooms.map((room) => <option value={room.id} key={room.id}>{room.name} · {room.format}</option>)}</select></label><label>Heure de début<input type="time" value={props.screeningTime} onChange={(e) => props.setScreeningTime(e.target.value)} /></label></div><label>Buffer pub / rotation<select value={props.bufferMinutes} onChange={(e) => props.setBufferMinutes(Number(e.target.value))}><option value={10}>10 min</option><option value={15}>15 min</option><option value={20}>20 min</option><option value={25}>25 min</option></select></label><div className="xinema-dialog__actions"><button type="button" className="xinema-secondary" onClick={props.onClose}>Annuler</button><button className="xinema-primary"><Check size={16} /> Planifier</button></div></form></div>; }
function Stat({ icon, value, label }: { icon: ReactNode; value: string; label: string }) { return <article className="xinema-stat"><span>{icon}</span><div><strong>{value}</strong><small>{label}</small></div></article>; }
