/// <reference lib="webworker" />
import Papa from 'papaparse';
import ExcelJS from 'exceljs';

type Row = Record<string, string>;
type Message = { type: 'build'; files: [string, File][]; cutoffDate: string; extractDate: string };
const names = ['Time Account.csv', 'Time Account-Time Account Details.csv', 'Time Account Snapshot.csv', 'Time Account Type.csv'];
const required: Record<string, string[]> = {
  'Time Account.csv': ['externalCode','userId','accountType.externalCode','accountClosed','startDate','endDate'],
  'Time Account-Time Account Details.csv': ['externalCode','timeAccountDetails.externalCode','timeAccountDetails.bookingDate','timeAccountDetails.bookingAmount'],
  'Time Account Snapshot.csv': ['userId','accountType.externalCode','balanceEffectiveDate','balance','outdated'],
  'Time Account Type.csv': ['externalCode','unit','minimumBalanceAllowed','simulateAccruals','snapshotsAllowed'],
};
const cut = (value = '') => value.trim().toLowerCase();
const groupKey = (...values: string[]) => values.join('\u001f');
const number = (value: string | undefined) => value === undefined || value === '' || Number.isNaN(Number(value)) ? null : Number(value);
const date = (value: string | undefined) => { const m = (value || '').trim().match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/); return m ? new Date(Date.UTC(+m[3], +m[1] - 1, +m[2])) : null; };
const day = (value: string) => new Date(`${value}T00:00:00Z`);

async function csv(file: File, name: string) {
  const parsed = await new Promise<Papa.ParseResult<Row>>((resolve, reject) => Papa.parse<Row>(file, { header: true, skipEmptyLines: true, transformHeader: (header) => header.replace(/^\uFEFF/, ''), complete: resolve, error: reject }));
  if (parsed.errors.length || required[name].some((column) => !parsed.meta.fields?.includes(column))) throw new Error(`Le fichier ${name} ne possède pas la structure SAP attendue.`);
  return parsed.data.filter((row) => (row['[OPERATOR]'] || '') === '');
}
function title(sheet: ExcelJS.Worksheet, titleText: string, subtitle: string, end: string) {
  sheet.mergeCells(`A1:${end}1`); sheet.mergeCells(`A2:${end}2`);
  [['A1', titleText, 'FF12343B', 18], ['A2', subtitle, 'FFDDEFF2', 10]].forEach(([cell, value, color, size]) => { const target = sheet.getCell(cell as string); target.value = value as string; target.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: color as string } }; target.font = { bold: cell === 'A1', color: { argb: cell === 'A1' ? 'FFFFFFFF' : 'FF1F2937' }, size: size as number }; target.alignment = { wrapText: true, vertical: 'middle' }; });
  sheet.getRow(1).height = 34; sheet.getRow(2).height = 30;
}
function header(sheet: ExcelJS.Worksheet, values: string[]) { sheet.getRow(4).values = values; sheet.getRow(4).height = 32; sheet.getRow(4).eachCell((cell) => { cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF12343B' } }; cell.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 9 }; cell.alignment = { wrapText: true, vertical: 'middle', horizontal: 'center' }; }); }
function widths(sheet: ExcelJS.Worksheet, values: number[]) { values.forEach((value, index) => sheet.getColumn(index + 1).width = value); }
function alert(row: any, cutoff: Date) {
  const critical: string[] = []; const info: string[] = []; const delta = row.snapshotBalance == null || row.postedAtSnapshot == null ? null : row.snapshotBalance - row.postedAtSnapshot;
  if (row.minimum != null && row.balance < row.minimum - .01) critical.push('SOUS MINIMUM CONFIGURÉ'); if (cut(row.outdated) === 'true') critical.push('SNAPSHOT OBSOLÈTE');
  if (delta != null && Math.abs(delta) > .01) { if (row.snapshotDate?.valueOf() === cutoff.valueOf() && cut(row.simulate) === 'false') critical.push('ÉCART SNAPSHOT À LA DATE D’ARRÊTÉ'); else if (cut(row.simulate) === 'true') info.push('ÉCART POSSIBLE LIÉ À LA SIMULATION'); else info.push('ÉCART SUR SNAPSHOT À ANALYSER'); }
  if (cut(row.snapshotsAllowed) === 'true' && !row.snapshotDate) critical.push('SNAPSHOT MANQUANT'); if (row.balance < -.01) info.push('SOLDE NÉGATIF'); if (!row.detailCount) info.push('AUCUNE ÉCRITURE À LA DATE D’ARRÊTÉ'); if (row.snapshotDate && row.snapshotDate < cutoff) info.push('SNAPSHOT ANTÉRIEUR');
  return { level: critical.length ? 'À vérifier' : info.length ? 'Information' : 'OK', text: [...critical, ...info].join(' ; ') || 'OK' };
}

async function build(files: Record<string, File>, cutoffDate: string, extractDate: string) {
  const cutoff = day(cutoffDate), extract = day(extractDate), [accounts, rawDetails, snapshots, types] = await Promise.all(names.map((name) => csv(files[name], name)));
  postMessage({ type: 'progress', label: 'Contrôle et dédoublonnage des écritures…', value: 26 });
  const detailsById = new Map<string, Row>(), duplicateGroups = new Map<string, Row[]>(); rawDetails.forEach((row) => { const id = row['timeAccountDetails.externalCode']; const group = duplicateGroups.get(id) || []; group.push(row); duplicateGroups.set(id, group); if (!detailsById.has(id)) detailsById.set(id, row); });
  const details = [...detailsById.values()], accountByCode = new Map<string, Row>(accounts.map((row) => [row.externalCode, row])), typeByCode = new Map<string, Row>(types.map((row) => [row.externalCode, row]));
  const active = accounts.filter((row) => cut(row.accountClosed) !== 'true' && (date(row.startDate)?.valueOf() || Infinity) <= cutoff.valueOf() && (date(row.endDate)?.valueOf() || Number.MAX_SAFE_INTEGER) >= cutoff.valueOf()); const activeCodes = new Set(active.map((row) => row.externalCode));
  const detailsByAccount = new Map<string, Row[]>(); details.forEach((row) => { if (activeCodes.has(row.externalCode)) { const group = detailsByAccount.get(row.externalCode) || []; group.push(row); detailsByAccount.set(row.externalCode, group); } });
  const accountsByPersonType = new Map<string, Row[]>(); accounts.forEach((row) => { const key = groupKey(row.userId, row['accountType.externalCode']), group = accountsByPersonType.get(key) || []; group.push(row); accountsByPersonType.set(key, group); });
  const cumulative = new Map<string, { at: Date; total: number }[]>(); details.forEach((row) => { const at = date(row['timeAccountDetails.bookingDate']), amount = number(row['timeAccountDetails.bookingAmount']); if (!at || amount == null) return; const group = cumulative.get(row.externalCode) || []; group.push({ at, total: amount }); cumulative.set(row.externalCode, group); }); cumulative.forEach((group) => { group.sort((a,b) => a.at.valueOf()-b.at.valueOf()); let total = 0; group.forEach((item) => { total += item.total; item.total = total; }); });
  const balanceAt = (account: string, at: Date) => (cumulative.get(account) || []).filter((item) => item.at <= at).at(-1)?.total || 0;
  const latestSnapshot = new Map<string, Row>(); snapshots.forEach((row) => { const at = date(row.balanceEffectiveDate), key = groupKey(row.userId,row['accountType.externalCode']), current = latestSnapshot.get(key); if (at && at <= cutoff && (!current || (date(current.balanceEffectiveDate) || new Date(0)) < at)) latestSnapshot.set(key,row); });
  postMessage({ type: 'progress', label: 'Reconstitution des soldes et rapprochement SAP…', value: 51 });
  const balances = active.map((account) => { const accountDetails = detailsByAccount.get(account.externalCode) || []; let balance = 0, move = 0, after = 0, detailCount = 0, last: Date | null = null; accountDetails.forEach((item) => { const at = date(item['timeAccountDetails.bookingDate']), amount = number(item['timeAccountDetails.bookingAmount']) || 0; if (!at) return; if (at <= cutoff) { balance += amount; detailCount++; if (!last || at > last) last = at; } else if (at <= extract) move += amount; else after += amount; }); const config = typeByCode.get(account['accountType.externalCode']); const snap = latestSnapshot.get(groupKey(account.userId,account['accountType.externalCode'])); const snapshotDate = snap ? date(snap.balanceEffectiveDate) : null; const postedAtSnapshot = snapshotDate ? (accountsByPersonType.get(groupKey(account.userId,account['accountType.externalCode'])) || []).filter((candidate) => cut(candidate.accountClosed) !== 'true' && (date(candidate.startDate)?.valueOf() || Infinity) <= snapshotDate.valueOf() && (date(candidate.endDate)?.valueOf() || Number.MAX_SAFE_INTEGER) >= snapshotDate.valueOf()).reduce((total,candidate) => total + balanceAt(candidate.externalCode,snapshotDate!),0) : null; const row: any = { userId:account.userId,country:config?.['country.code'] || account['accountType.externalCode'].split('_')[0],type:account['accountType.externalCode'],label:config?.['externalName.fr_FR'] || config?.['externalName.defaultValue'] || config?.['externalName.en_US'] || '',unit:config?.unit || accountDetails[0]?.['timeAccountDetails.bookingUnit'] || 'NON DISPONIBLE',code:account.externalCode,start:date(account.startDate),end:date(account.endDate),bookingStart:date(account.bookingStartDate),bookingEnd:date(account.bookingEndDate),balance,move,after,detailCount,last,snapshotDate,snapshotBalance:snap ? number(snap.balance) : null,outdated:snap?.outdated || '',postedAtSnapshot,minimum:config ? number(config.minimumBalanceAllowed) : null,simulate:config?.simulateAccruals || '',snapshotsAllowed:config?.snapshotsAllowed || '',config:config ? 'Oui' : 'Non'}; return { ...row, ...alert(row,cutoff) }; }).sort((a,b) => groupKey(a.country,a.type,a.userId,a.code).localeCompare(groupKey(b.country,b.type,b.userId,b.code)));
  const future = details.filter((row) => activeCodes.has(row.externalCode) && (date(row['timeAccountDetails.bookingDate']) || new Date(0)) > cutoff).map((row) => { const account = accountByCode.get(row.externalCode)!, config = typeByCode.get(account['accountType.externalCode']), at = date(row['timeAccountDetails.bookingDate'])!; return [account.userId,config?.['country.code'] || account['accountType.externalCode'].split('_')[0],account['accountType.externalCode'],config?.['externalName.fr_FR'] || config?.['externalName.defaultValue'] || '',config?.unit || row['timeAccountDetails.bookingUnit'],account.externalCode,at,row['timeAccountDetails.bookingType'],number(row['timeAccountDetails.bookingAmount']),row['timeAccountDetails.employeeTime.externalCode'],row['timeAccountDetails.calendarEntry.externalCode'],row['timeAccountDetails.referenceObject'],row['timeAccountDetails.comment'],row['timeAccountDetails.externalCode'],at <= extract ? 'Après arrêté jusqu’à extraction' : 'Après extraction']; });
  const duplicates = [...duplicateGroups.entries()].filter(([,rows]) => rows.length > 1).map(([id,rows]) => { const row = rows[0], account = accountByCode.get(row.externalCode); return [id,rows.length,row.externalCode,account?.userId || '',account?.['accountType.externalCode'] || '',date(row['timeAccountDetails.bookingDate']),row['timeAccountDetails.bookingType'],number(row['timeAccountDetails.bookingAmount']),row['timeAccountDetails.bookingUnit'],row['timeAccountDetails.comment']]; });
  const summary = { rawDetailRows:rawDetails.length,uniqueDetailRows:details.length,duplicateRowsRemoved:rawDetails.length-details.length,activeAccounts:balances.length,uniqueUsers:new Set(balances.map(row=>row.userId)).size,uniqueTypes:new Set(balances.map(row=>row.type)).size,futureMovementRows:future.length,reviewAccounts:balances.filter(row=>row.level==='À vérifier').length };
  postMessage({ type: 'progress', label: 'Construction des cinq onglets Excel…', value: 74 });
  const workbook = new ExcelJS.Workbook(); workbook.creator = 'XIRH Time Off Control'; const label = cutoffDate.split('-').reverse().join('/'), extraction = extractDate.split('-').reverse().join('/');
  const overview = workbook.addWorksheet('Synthèse',{views:[{state:'frozen',ySplit:20,showGridLines:false}]}), soldes = workbook.addWorksheet(`Soldes au ${cutoffDate.slice(8,10)}-${cutoffDate.slice(5,7)}`,{views:[{state:'frozen',xSplit:6,ySplit:4,showGridLines:false}]}), mouvements = workbook.addWorksheet(`Mouvements > ${cutoffDate.slice(8,10)}-${cutoffDate.slice(5,7)}`,{views:[{state:'frozen',xSplit:6,ySplit:4,showGridLines:false}]}), controls = workbook.addWorksheet('Contrôles',{views:[{state:'frozen',ySplit:4,showGridLines:false}]}), duplicatesSheet = workbook.addWorksheet('Doublons écartés',{views:[{state:'frozen',ySplit:4,showGridLines:false}]});
  const balanceHeaders=['User ID','Pays / préfixe','Type de compteur','Libellé (si exporté)','Unité','External Code du compte','Valide du','Valide au','Réservable du','Réservable au',`Solde calculé au ${label}`,`Mouv. après arrêté au ${extraction}`,`Mouv. après ${extraction}`,'Solde projeté selon l’export',`Nb écritures ≤ ${label}`,`Dernière écriture ≤ ${label}`,`Date dernier snapshot ≤ ${label}`,'Solde du snapshot',`Snapshot exact au ${label}`,'Snapshot outdated','Solde écritures à la date du snapshot','Écart de contrôle snapshot','Minimum configuré','Simulate Accruals','Snapshots autorisés','Configuration du type disponible','Niveau de contrôle','Alertes / informations']; title(soldes,`Soldes des compteurs au ${label}`,`Périmètre : comptes ouverts et valides au ${label}. Les soldes reposent sur les écritures uniques.`, 'AB'); header(soldes,balanceHeaders); widths(soldes,[12,12,23,28,9,34,12,12,12,12,16,17,17,17,13,16,17,15,15,14,18,16,15,15,15,18,16,48]); balances.forEach((row,index)=>{const i=index+5;soldes.addRow([row.userId,row.country,row.type,row.label,row.unit,row.code,row.start,row.end,row.bookingStart,row.bookingEnd,row.balance,row.move,row.after,{formula:`K${i}+L${i}+M${i}`},row.detailCount,row.last,row.snapshotDate,row.snapshotBalance,row.snapshotDate?.valueOf()===cutoff.valueOf()?'Oui':'Non',row.outdated ? cut(row.outdated)==='true'?'Oui':'Non':'',row.postedAtSnapshot,{formula:`IF(OR(Q${i}="",R${i}="",U${i}=""),"",R${i}-U${i})`},row.minimum,row.simulate,row.snapshotsAllowed,row.config,row.level,row.text]);}); soldes.autoFilter={from:'A4',to:`AB${Math.max(4,balances.length+4)}`}; [7,8,9,10,16,17].forEach(i=>soldes.getColumn(i).numFmt='yyyy-mm-dd');[11,12,13,14,18,21,22,23].forEach(i=>soldes.getColumn(i).numFmt='0.00########'); soldes.getColumn(28).alignment={wrapText:true,vertical:'top'};
  const futureHeaders=['User ID','Pays / préfixe','Type de compteur','Libellé (si exporté)','Unité','External Code du compte','Posting Date','Posting Type','Montant','Employee Time ID','Calendar Entry ID','Reference Object','Commentaire','External Code du détail','Période'];title(mouvements,`Mouvements datés après le ${label}`,`Détail des écritures uniques postérieures à la date d’arrêté.`, 'O');header(mouvements,futureHeaders);widths(mouvements,[12,12,23,28,9,34,16,28,13,34,34,28,40,34,25]);future.forEach(row=>mouvements.addRow(row));mouvements.autoFilter={from:'A4',to:`O${Math.max(4,future.length+4)}`};mouvements.getColumn(7).numFmt='yyyy-mm-dd';mouvements.getColumn(9).numFmt='0.00########';
  const duplicateHeaders=['External Code du détail','Occurrences brutes','External Code du compte','User ID','Type de compteur','Posting Date','Posting Type','Montant','Unité','Commentaire'];title(duplicatesSheet,'Écritures dupliquées écartées','Une seule occurrence par external code de détail est conservée dans tous les calculs.','J');header(duplicatesSheet,duplicateHeaders);widths(duplicatesSheet,[35,14,35,14,25,16,30,13,10,45]);duplicates.forEach(row=>duplicatesSheet.addRow(row));duplicatesSheet.autoFilter={from:'A4',to:`J${Math.max(4,duplicates.length+4)}`};duplicatesSheet.getColumn(6).numFmt='yyyy-mm-dd';duplicatesSheet.getColumn(8).numFmt='0.00########';
  title(overview,`Synthèse des compteurs au ${label}`,'Une vue de contrôle locale : les unités ne sont jamais additionnées entre elles.','M'); overview.getCell('A4').value='Paramètres';overview.getCell('A5').value='Date d’arrêté';overview.getCell('B5').value=cutoff;overview.getCell('A6').value='Date de l’export';overview.getCell('B6').value=extract;overview.getCell('B5').numFmt=overview.getCell('B6').numFmt='yyyy-mm-dd';overview.getCell('D4').value='Indicateurs clés';[['Comptes inclus',summary.activeAccounts],['Salariés',summary.uniqueUsers],['Types de compte',summary.uniqueTypes],['Écritures brutes',summary.rawDetailRows],['Écritures uniques',summary.uniqueDetailRows],['Doublons écartés',summary.duplicateRowsRemoved],['Mouvements postérieurs',summary.futureMovementRows],['Lignes à vérifier',summary.reviewAccounts]].forEach(([a,b],i)=>{overview.getCell(5+i,4).value=a as string;overview.getCell(5+i,5).value=b as number;});overview.mergeCells('A19:M19');overview.getCell('A19').value='Synthèse par type de compte';header(overview,['Pays / préfixe','Type de compteur','Libellé','Unité','Comptes','Salariés',`Solde total ${label}`,'Négatifs',`Mouv. au ${extraction}`,`Mouv. après ${extraction}`,'Snapshot exact','Snapshot outdated','À vérifier']);const typeGroups=new Map<string,any[]>();balances.forEach(row=>{const k=groupKey(row.country,row.type,row.label,row.unit),g=typeGroups.get(k)||[];g.push(row);typeGroups.set(k,g)});[...typeGroups.values()].forEach(g=>{const r=g[0];overview.addRow([r.country,r.type,r.label,r.unit,g.length,new Set(g.map(x=>x.userId)).size,g.reduce((t,x)=>t+x.balance,0),g.filter(x=>x.balance<-.01).length,g.reduce((t,x)=>t+x.move,0),g.reduce((t,x)=>t+x.after,0),g.filter(x=>x.snapshotDate?.valueOf()===cutoff.valueOf()).length,g.filter(x=>cut(x.outdated)==='true').length,g.filter(x=>x.level==='À vérifier').length])});overview.autoFilter={from:'A20',to:`M${Math.max(20,overview.rowCount)}`};widths(overview,[25,28,28,15,14,14,17,12,18,18,15,16,14]);
  title(controls,'Méthode et contrôles qualité','Ce fichier explicite les règles appliquées et les alertes à interpréter avec le contexte SAP.','H');controls.getCell('A4').value='Méthode de calcul';[['Périmètre des comptes',`accountClosed ≠ true ET startDate ≤ ${label} ET endDate ≥ ${label}.`],['Dédoublonnage','Une occurrence conservée par timeAccountDetails.externalCode.'],['Solde à date',`Somme des bookingAmount uniques dont bookingDate ≤ ${label}.`],['Mouvements postérieurs',`Séparation entre arrêté et extraction (${extraction}), puis les écritures après extraction.`],['Snapshot','Dernier snapshot de salarié/type à la date d’arrêté ou avant.'],['Écart snapshot','Comparaison avec les écritures cumulées à la date propre du snapshot.']].forEach(row=>controls.addRow(row));controls.getCell('A14').value='Contrôles qualité';header(controls,['Contrôle','Résultat','Statut','Lecture']);[['Écritures brutes',summary.rawDetailRows,'Information','Volume avant nettoyage.'],['Écritures uniques',summary.uniqueDetailRows,'OK','Base utilisée pour les calculs.'],['Lignes dupliquées écartées',summary.duplicateRowsRemoved,'Traité','Une occurrence est conservée par identifiant MDF.'],['Écritures orphelines',details.filter(row=>!accountByCode.has(row.externalCode)).length,details.some(row=>!accountByCode.has(row.externalCode))?'À vérifier':'OK','Détails sans compte parent.'],['Snapshots outdated',balances.filter(row=>cut(row.outdated)==='true').length,balances.some(row=>cut(row.outdated)==='true')?'À vérifier':'OK','Snapshot signalé obsolète par SAP.'],['Comptes classés À vérifier',summary.reviewAccounts,summary.reviewAccounts?'À vérifier':'OK','Snapshots, minimums ou écarts à analyser.'],['Mouvements postérieurs',summary.futureMovementRows,'Information','Non inclus dans le solde à la date d’arrêté.']].forEach(row=>controls.addRow(row));widths(controls,[35,18,16,72]);controls.getColumn(4).alignment={wrapText:true,vertical:'top'};
  postMessage({ type: 'progress', label: 'Finalisation sécurisée du classeur…', value: 94 }); const buffer = await workbook.xlsx.writeBuffer(); return { buffer: buffer as ArrayBuffer, filename:`Soldes_compteurs_Time_Off_au_${cutoffDate}.xlsx`, summary };
}
self.onmessage = async (event: MessageEvent<Message>) => { try { const files = Object.fromEntries(event.data.files) as Record<string,File>; if (names.some(name=>!files[name])) throw new Error('Les quatre exports SAP sont requis.'); const report = await build(files,event.data.cutoffDate,event.data.extractDate); postMessage({type:'complete',...report},[report.buffer]); } catch (error) { postMessage({type:'error',message:error instanceof Error ? error.message : 'La génération locale a rencontré une erreur.'}); } };
